services:
  lab:
    image: ghcr.io/bozdogalex/big-data-cloud-iot-upt@sha256:e678ecb78658d8b77d2b2955bd7b088c4f555167ed3eeec73955d96dced8b2c5
    platform: linux/amd64
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - lab-work-2026-09-21-v3:/workspace/labs

volumes:
  lab-work-2026-09-21-v3:
